name: CI

on:
  merge_group:
  pull_request:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: Build
    strategy:
      matrix:
        node-version: [16.x, 18.x]
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 7.27.0
      - name: Install with pnpm
        run: pnpm install
      - name: Lint code
        run: pnpm lint
      - name: Build
        run: pnpm build
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: pnpm/action-setup@v2
        with:
          version: 7.27.0
      - name: Install with pnpm
        run: pnpm install
      - name: Run tests
        run: pnpm test:ci
      - name: Copy json coverage report
        run: |
          mkdir -p coverage
      # cp ./lib/libname/coverage/coverage-final.json ./coverage/coverage-libname.json
      # cp ./lib/libname/coverage/coverage-final.json ./coverage/coverage-libname.json
      # cp ./lib/libname/coverage/coverage-final.json ./coverage/coverage-libname.json
      - name: Merge json coverage reports
        run: pnpm dlx nyc merge coverage coverage/merged-coverage.json
      - name: Convert json coverage report to lcov
        run: pnpm dlx nyc report --reporter=lcov --temp-directory=coverage
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage/lcov.info
